language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
before_install:
  - sudo apt-get install wireless-tools
  - sudo pip install -U pip wheel setuptools
  - sudo pip install -U mock
install:
  - sudo python setup.py -q install
# command to run tests
script: sudo python setup.py test
